services:
  api1:
    build: .
    hostname: api1
    platform: linux/amd64
    environment:
      - API_SOCKET=/var/run/rinha/api1.sock
    volumes:
      - socket-dir:/var/run/rinha
    networks:
      - fraud-network
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "160MB"

  api2:
    build: .
    hostname: api2
    platform: linux/amd64
    environment:
      - API_SOCKET=/var/run/rinha/api2.sock
    volumes:
      - socket-dir:/var/run/rinha
    networks:
      - fraud-network
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "160MB"

  haproxy:
    image: haproxy:3.0-alpine
    hostname: haproxy
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - socket-dir:/var/run/rinha
    depends_on:
      - api1
      - api2
    networks:
      - fraud-network
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

networks:
  fraud-network:
    driver: bridge

volumes:
  socket-dir:
