services:
  api1:
    image: henriqueyda/rinha-backend-2026:2
    hostname: api1
    platform: linux/amd64
    environment:
      - API_SOCKET=/var/run/rinha/api1.sock
    volumes:
      - vol:/var/run/rinha
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api2:
    image: henriqueyda/rinha-backend-2026:2
    hostname: api2
    platform: linux/amd64
    environment:
      - API_SOCKET=/var/run/rinha/api2.sock
    volumes:
      - vol:/var/run/rinha
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  haproxy:
    image: haproxy:3.0-alpine
    hostname: haproxy
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - vol:/var/run/rinha
    depends_on:
      - api1
      - api2
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

networks:
  network:
    driver: bridge

volumes:
  vol:
