events {
    worker_connections 4096; # Aumentado para aguentar o tráfego do teste de carga
}

http {
    upstream api {
        server api1:8080;
        server api2:8080;

        # 1. Define quantas conexões IDLE (inativas/vivas) o Nginx vai manter 
        # abertas com os seus backends Go por worker process.
        keepalive 1024;
        keepalive_requests 100000;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api;

            # 2. OBRIGATÓRIO: Força o Nginx a usar HTTP/1.1 com o Go
            # (O padrão do proxy_pass é HTTP/1.0, que não suporta keepalive)
            proxy_http_version 1.1;

            # 3. OBRIGATÓRIO: Limpa o cabeçalho Connection.
            # Se o seu teste de carga enviar "Connection: close", isso impede 
            # que o Nginx repasse esse "close" para o seu servidor Go.
            proxy_set_header Connection "";
            
            # Opcional: Melhora o repasse de IPs originais para o Go
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}



# events {}

# http {
#     upstream api {
#         server api1:8080;
#         server api2:8080;
#     }

#     server {
#         listen 9999;

#         location / {
#             proxy_pass http://api;
#         }
#     }
# }